### ISSUE TITLE
Replace the micro32 module with an onboard esp32 pico d4

### ISSUE THREAD

**Issue by uvwxy** [Open-Smartwatch/open-smartwatch-light#3]
The thickest part of the current design is the ttgo micro-32 module. If we place the esp pico d4 chip directly on the PCB we would get more space to maybe add additional ram (see GPS edition on how to add ram).

**Comment by Electro707** [comment]
There is also the [ESP32­PICO­MINI­02](https://www.espressif.com/sites/default/files/documentation/esp32-pico-mini-02_datasheet_en.pdf) by Espressif, which is slightly smaller than the current module used (13.2×16.6×2.4mm).

Also by thickest you mean the biggest in size?

**Comment by uvwxy** [comment]
> Also by thickest you mean the biggest in size?

yes.

**Comment by uvwxy** [comment]
I'm also looking at developing a custom module fitting the footprint, that already includes the PSRAM for an additional 4MB RAM

**Comment by uvwxy** [comment]
Update: the custom module is not going to work in a nice way.

**Comment by Sharealikelicence** [comment]
Only issue I can see with this is getting FCC approval for the design to pass the RF leakage regulations etc.

**Comment by Electro707** [comment]
> Only issue I can see with this is getting FCC approval for the design to pass the RF leakage regulations etc.

Well that should only apply if the watch is sold (and not as a kit). Otherwise as long as it's not poorly designed it shouldn't need approval/official testing (maybe tough a home-made test should be done just to make sure it doesn't spew crap out). At least as far as I'm aware.

**Comment by Sharealikelicence** [comment]
Definitely not my field of expertise, but why does the micro32 board have FCC compliance as it is arguably sold in kit form? I'm thinking, for any commercial partners to pick up the design, RF leakage tests will have to be performed otherwise they probably won't take it on? I have no idea about that though.

**Comment by Electro707** [comment]
Because the Micro32 is not sold as a kit, but instead as a module to be incorporated in a product. The advantage of the FCC compliance there is that the OEM using the module won't have to certify it for whatever certifications for intentional radiators it needs (they still need to do a Part15 non-intential radiator compliance, but that's one less certification/testing they need to do). As least as far as I'm aware.

As for this project, official FCC certification won't be required as it's not being sold (and if it is, it's done so as a hobbyist-oriented kit which is exempt from needing official certifications).

**Comment by Sharealikelicence** [comment]
Yeah, I was thinking mainly designing it so it "should" pass FCC compliance, not actually do it. My original thought was to just duplicate the micro32 design onto the board. But, it's not open source, from what I can find, and I'm not sure about the copper layer count etc.

**Comment by carlos-ramos-73** [comment]
> There is also the [ESP32­PICO­MINI­02](https://www.espressif.com/sites/default/files/documentation/esp32-pico-mini-02_datasheet_en.pdf) by Espressif, which is slightly smaller than the current module used (13.2×16.6×2.4mm).
> 

I took a look into the ESP32 PICO MINI 02, It looks very promising for a replacement with the exception of the pads for soldering. Which, for an open source hobby kit, I think is a big deal when it comes to accessibility. But I do agree that if we can make it smaller, then it might be worth the tradeoff.

**Comment by uvwxy** [comment]
Done with the latest design:

![IMG_0471_1024](https://user-images.githubusercontent.com/930238/173010895-3eb2bdfa-3b63-46c0-b96a-26e09277b225.jpg)

(there are still some bugs I need to resolve in the design. Patience ;) )
