### ISSUE TITLE
Is it an option to customise the watch?

### ISSUE THREAD

**Issue by NavehKh** [Open-Smartwatch/open-smartwatch-light#6]
Hi,

We are two friends in high school and we learn in a special program for youth at the university. As a final year project we chose to create a watch that has an alarm for deaf people.

The idea was to create a hand watch with pulse and movement sensors, a microphone, and a small electric shocker. When the time's up the watch sends little electric shocks until our guy is awake (what we learn from the sensors).

We looked all over the internet and we decided to use this DIY smartwatch as a basis for our project (this one - https://open-smartwatch.github.io/). It looked great, very functional and we can see you put a lot of effort in it.

We would like to know: can we plug the pulse sensor, the microphone, and the electric shocker to your open source smartwatch? Does the controlling unit (the ESP32-pico-D4) have input and output plugs that will allow us to connect the sensors to the watch?
If all the above are possible, we would like to get some help how to do it 🙏.

Thanks a lot in advance,

Eitan Givon and Naveh Khagbi

**Comment by Electro707** [comment]
Assuming that the pulse sensor is an analog output, the module does have an internal ADC that can be used for that
For the shocker, depends on what it needs. If a 3.3v power rail will suffice, it can be done with a transistor switch configuration to drive it. Otherwise an internal boost converter can be used.
For the microphone, I would recommend some external microphone -> (I2C, SPI, or I2S) driver/interface as the internal ADC might not be fast enough for audio.

The watch PCB doesn't have pads to solder other stuff to it. And while you can hack in magnet wires to the ESP module and have an external circuitry for your peripherals, I would recommend forking the design and changing the PCB to fit your needs.
